[build]
  command = "npx prisma db push && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  GEMINI_API_KEY = "AIzaSyCEFKWf_YzNaIY4V2rq0BndLC8ucp4bfpA"

[[plugins]]
  package = "@netlify/plugin-nextjs"
