"use server";

import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { revalidatePath } from "next/cache";
import bcrypt from "bcrypt";
import crypto from "crypto";

const createFishermanSchema = z.object({
  firstName: z.string().min(1, "First name is required"),
  lastName: z.string().min(1, "Last name is required"),
  email: z.string().email("Invalid email address"),
  barangay: z.string().min(1, "Barangay is required"),
  contactNumber: z.string().min(1, "Contact number is required"),
  password: z.string().optional(),
});

export async function getFishermen(page = 1, pageSize = 20) {
  try {
    const skip = (page - 1) * pageSize;
    const [fishermen, total] = await Promise.all([
      prisma.fisherman.findMany({
        skip,
        take: pageSize,
        include: {
          user: true,
          catches: {
            include: {
              details: true,
            },
          },
        },
        orderBy: { id: "desc" },
      }),
      prisma.fisherman.count(),
    ]);

    const result = fishermen.map((f) => {
      const totalWeight = f.catches.reduce((acc, c) => {
        return acc + c.details.reduce((sum, d) => sum + d.weight, 0);
      }, 0);

      return {
        id: f.id,
        name: `${f.user.firstName} ${f.user.lastName}`,
        email: f.user.email,
        barangay: f.barangay,
        contactNumber: f.contactNumber,
        totalWeight,
        initials: `${f.user.firstName[0]}${f.user.lastName[0]}`.toUpperCase(),
      };
    });

    return { data: result, total, page, pageSize };
  } catch (error) {
    console.error("Error fetching fishermen:", error);
    return [];
  }
}

export async function createFisherman(data: {
  firstName: string;
  lastName: string;
  email: string;
  barangay: string;
  contactNumber: string;
  password?: string;
}) {
  try {
    const validated = createFishermanSchema.parse(data);

    const staffRole = await prisma.role.findUnique({ where: { name: "staff" } });
    if (!staffRole) {
      throw new Error("Required role 'staff' not found. Please seed the database.");
    }

    const isAutoGenerated = !data.password;
    const plainPassword = data.password || crypto.randomBytes(6).toString("hex");
    const hashedPassword = await bcrypt.hash(plainPassword, 10);

    const result = await prisma.$transaction(async (tx) => {
      const user = await tx.user.create({
        data: {
          firstName: validated.firstName,
          lastName: validated.lastName,
          email: validated.email,
          password: hashedPassword,
          roleId: staffRole.id,
        },
      });

      const fisherman = await tx.fisherman.create({
        data: {
          id: user.id,
          barangay: validated.barangay,
          contactNumber: validated.contactNumber,
        },
      });

      return { ...fisherman, plainPassword: isAutoGenerated ? plainPassword : undefined };
    });

    revalidatePath("/fishermen");
    return { success: true, data: result, plainPassword: isAutoGenerated ? plainPassword : undefined };
  } catch (error: unknown) {
    console.error("Error creating fisherman:", error);
    const message = error instanceof Error ? error.message : "Failed to create fisherman";
    return { success: false, error: message };
  }
}

export async function getFishermanById(id: string) {
  try {
    const fisherman = await prisma.fisherman.findUnique({
      where: { id },
      include: {
        user: true,
      },
    });

    if (!fisherman) {
      return { success: false, error: "Fisherman not found" };
    }

    return {
      success: true,
      data: {
        id: fisherman.id,
        firstName: fisherman.user.firstName,
        lastName: fisherman.user.lastName,
        email: fisherman.user.email,
        barangay: fisherman.barangay,
        contactNumber: fisherman.contactNumber,
      },
    };
  } catch (error: unknown) {
    console.error("Error fetching fisherman:", error);
    const message = error instanceof Error ? error.message : "Failed to fetch fisherman";
    return { success: false, error: message };
  }
}

export async function updateFisherman(id: string, data: {
  firstName?: string;
  lastName?: string;
  email?: string;
  barangay?: string;
  contactNumber?: string;
  password?: string;
}) {
  try {
    const result = await prisma.$transaction(async (tx) => {
      const updateUser: { firstName?: string; lastName?: string; email?: string; password?: string } = {};
      if (data.firstName) updateUser.firstName = data.firstName;
      if (data.lastName) updateUser.lastName = data.lastName;
      if (data.email) updateUser.email = data.email;
      if (data.password) updateUser.password = await bcrypt.hash(data.password, 10);

      if (Object.keys(updateUser).length > 0) {
        await tx.user.update({
          where: { id },
          data: updateUser,
        });
      }

      const updateFisherman: { barangay?: string; contactNumber?: string } = {};
      if (data.barangay) updateFisherman.barangay = data.barangay;
      if (data.contactNumber) updateFisherman.contactNumber = data.contactNumber;

      if (Object.keys(updateFisherman).length > 0) {
        await tx.fisherman.update({
          where: { id },
          data: updateFisherman,
        });
      }

      return { success: true };
    });

    revalidatePath("/fishermen");
    return result;
  } catch (error: unknown) {
    console.error("Error updating fisherman:", error);
    const message = error instanceof Error ? error.message : "Failed to update fisherman";
    return { success: false, error: message };
  }
}

export async function deleteFisherman(id: string) {
  try {
    await prisma.$transaction(async (tx) => {
      await tx.fisherman.delete({ where: { id } });
      await tx.user.delete({ where: { id } });
    });

    revalidatePath("/fishermen");
    return { success: true };
  } catch (error: unknown) {
    console.error("Error deleting fisherman:", error);
    const message = error instanceof Error ? error.message : "Failed to delete fisherman";
    return { success: false, error: message };
  }
}
